### ISSUE TITLE
TestBwscan test hangs after succeeding

### ISSUE THREAD

**Issue by DonnchaC** [TheTorProject/bwscanner#22]
The `TestBwscan` test runs the `BwScan` class to scan and collect measurements across a set of relays. This test is currently passing. However the trial test runner hangs after the test completes which causes the test suite to fail with a timeout error.

I'm not sure what is causing it to hang but its possible some Deferred or callLater which is not being cleaned up properly when the measurements finish.

**Comment by aagbsn** [comment]
This was fixed in PR #69
