### ISSUE TITLE
Improve logging options for tor

### ISSUE THREAD

**Issue by teor2345** [TheTorProject/bwscanner#55]
We should check the legacy bwauth torrc options, and copy any relevant ones across:
https://gitweb.torproject.org/torflow.git/tree/NetworkScanners/BwAuthority/data/tor.1/torrc

In particular:
SafeLogging 0
LogTimeGranularity 1
DisableDebuggerAttachment 0
(Those last two are from chutney, see https://gitweb.torproject.org/chutney.git/tree/torrc_templates/common.i )

**Comment by juga0** [comment]
Closing this issue as #68 has been merged.
