### ISSUE TITLE
Add code coverage measurement

### ISSUE THREAD

**Issue by DonnchaC** [TheTorProject/bwscanner#7]
A service such as Coveralls should give us a good idea about how we are doing with tests.

**Comment by david415** [comment]
yes and you can also run coverage locally if you don't want to wait for travis ci to do it.
here's how i use coverage on my workstation:

```
(virtenv-bwscanner) user@subgraph:~/code/bwscanner$ coverage run --source=. /home/user/virtenv-bwscanner/bin/trial --reporter=verbose test
cuv graph
...
```

cuv, the cli tool is pretty sweet.
https://meejah.ca/projects/cuvner
