### ISSUE TITLE
OpenSSL Error

### ISSUE THREAD

**Issue by juga0** [TheTorProject/bwscanner#75]
`scan` gives OpenSSL error for some relays:
    2018-01-29T14:34:57+0000 [WARN]: Download failed for router  $6F33E92A67EC038B559415AC56C860075F6D287F: <twisted.python.failure.Failure twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]>]>.

Check the TLS options in the fetch agent

**Comment by juga0** [comment]
The agent is defined in https://github.com/juga0/bwscanner/blob/develop/bwscanner/fetcher.py#L76.

In theory twisted should be using the certificates system path in `trustRoot` (https://twistedmatrix.com/documents/17.1.0/api/twisted.web.client.BrowserLikePolicyForHTTPS.html)

**Comment by meejah** [comment]
What OS are you running this on?

**Comment by juga0** [comment]
Debian, so cacert is missing, but that shouldn't be the issue.

**Comment by meejah** [comment]
Another thing to try would be the now built-in txtorcon agent, available via `Tor.web_agent()` or `Circuit.web_agent()` (the latter uses the given circuit only).

**Comment by meejah** [comment]
Yeah IME Debian works fine. You could try installing `certifi` (Python package) but .. shouldn't need to?

**Comment by juga0** [comment]
Actually i tried `SSL_CERT_FILE="$(python -m certifi)"` as explained in https://github.com/twisted/treq/issues/94, and then i didn't get this error, but still this shouldn't be needed...

**Comment by juga0** [comment]
Running `Circuit.web_agent()` in this example https://github.com/meejah/txtorcon/blob/master/examples/web_client_custom_circuit.py#L47 also gives certificate error.
Maybe twisted version we are using here (16.0.2)?. I'll try with others.

**Comment by juga0** [comment]
Last version also gives the error.

**Comment by meejah** [comment]
Do you have the "ca-certificates" package installed in Debian?

**Comment by juga0** [comment]
Yes.

**Comment by juga0** [comment]
Upgrading pyOpenSSL to 17.5.0 seems to solve the issue.
