### ISSUE TITLE
Chutney create more exits than non-exits relays

### ISSUE THREAD

**Issue by juga0** [TheTorProject/bwscanner#95]
The default configuration in chutney for networks/basic-025 [0] creates 16 exits and only 4 non-exits relays (that are actually authorities). 
Maybe it should be provided a custom chutney configuration file, since in the production Tor the there are more non-exit relays than exits?
The custom configuration file could be something like 14 relays and 2 exits? (assuming 1 exit per 7 relays)
Maybe this also has to do with #95?.
[0] https://github.com/torproject/chutney/blob/master/networks/basic-025#L6

**Comment by teor2345** [comment]
> Maybe it should be provided a custom chutney configuration file, since in the production Tor the there are more non-exit relays than exits?

If you create a ticket in the Core Tor/Chutney component on
https://bugs.torproject.org , I will review and merge this network to chutney.

**Comment by juga0** [comment]
Thanks for the feedback. Created #25228

**Comment by juga0** [comment]
Closing this as a new configuration has been created in chutney (https://trac.torproject.org/projects/tor/ticket/25228).
New bugs running tests with this configuration in #97
