### ISSUE TITLE
Simplify code using txtorcon new features

### ISSUE THREAD

**Issue by juga0** [TheTorProject/bwscanner#98]
This would also eliminated txsocksx dependency and make bwscanner compatible with python 3, as commented in #90.
WIP in branch https://github.com/TheTorProject/bwscanner/commit/e0efe0af473a3b3152e60b6619617f074a077fca
Code not being used after those changes in branch https://github.com/juga0/bwscanner/commit/fd4e1465b42db8326fe4373b2fad3e0d6af840ac

**Comment by aagbsn** [comment]
see https://github.com/TheTorProject/bwscanner/tree/use_txtorcon_web_agent (edit, oops)

**Comment by juga0** [comment]
Fixed by #101
